echo '# The Coming Great Reset in Programming' >'The Coming Great Reset in Programming.md'
echo '# Goal of Programming' >'Goal of Programming.md'
echo '# 1950s Reality' >'1950s Reality.md'
echo '# 2022 Reality' >'2022 Reality.md'
echo '# Current Technology' >'Current Technology.md'
echo '# Canaries in the Coal Mines' >'Canaries in the Coal Mines.md'
echo '# Bloatware' >'Bloatware.md'
echo '# Programming Languages Are IDEs' >'Programming Languages Are IDEs.md'
echo '# Type Checking vs. Syntax Checking' >'Type Checking vs. Syntax Checking.md'
echo '# Mathematics' >'Mathematics.md'
echo '# Mathematical Notation' >'Mathematical Notation.md'
echo '# New Notation' >'New Notation.md'
echo '# Multiple Notations (Syntax Skins)' >'Multiple Notations.md'
echo '# DaS' >'DaS.md'
ECHO '# SVG' >'SVG.MD'
echo '# Backtracking' >'Backtracking.md'
ECHO '# PEG' >'PEG.MD'
echo '# Syntax is Cheap' >'Syntax is Cheap.md'
echo '# Orthogonal Programming Languages' >'Orthogonal Programming Languages.md'
ECHO '# S/SL' >'SSL.MD'
echo '# Optimization in Compilers' >'Optimization in Compilers.md'
echo '# Concurrency and Greenspun"s 10th Rule' >'Concurrency and Greenspuns 10th Rule.md'
echo '# Avoid If-Then-Else' >'Avoid If-Then-Else.md'
echo '# Macros for Non-Lisp Language' >'Macros for Non-Lisp Language.md'
ECHO '# FAB' >'FAB.MD'
echo '# Mutation' >'Mutation.md'
echo '# Thread Safety' >'Thread Safety.md'
ECHO '# GC' >'GC.MD'
echo '# Allocation' >'Allocation.md'
echo '# Layers of Notation' >'Layers of Notation.md'
echo '# Clockwork' >'Clockwork.md'
ECHO '# DIRT' >'DIRT.MD'
ECHO '# 0D' >'0D.MD'
echo '# Structured Message Passing' >'Structured Message Passing.md'
echo '# Engineering' >'Engineering.md'
echo '# Notes:' >'Notes.md'
